### ISSUE TITLE
I cannot install mdx-mermaid plugin

### ISSUE THREAD

**Issue by alexandrehtrb** [sjwall/mdx-mermaid#64]
**Describe the bug**
I cannot setup the mdx-mermaid plugin in my Docusaurus website.

**To Reproduce**
1. `npx create-docusaurus@latest my-website classic --typescript`
2. `npm install mdx-mermaid mermaid`
3. In the `docusaurus.config.js` file, in the config object, add the plugin:

```js
const config = {
  ...
  plugins: ['mdx-mermaid']
}
```
4. `npm start`

**Stack trace**
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> my-website@0.0.0 start
> docusaurus start

[INFO] Starting the development server...
[ERROR] Error [ERR_REQUIRE_ESM]: require() of ES Module C:\PROJETOS\TesteDocusaurus\my-website\node_modules\mdx-mermaid\lib\mdxast-mermaid.js from C:\PROJETOS\TesteDocusaurus\my-website\node_modules\@docusaurus\core\lib\server\plugins\configs.js not supported.
Instead change the require of mdxast-mermaid.js in C:\PROJETOS\TesteDocusaurus\my-website\node_modules\@docusaurus\core\lib\server\plugins\configs.js to a dynamic import() which is available in all CommonJS modules.
    at module.exports (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\import-fresh\index.js:32:59)
    at normalizePluginConfig (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\@docusaurus\core\lib\server\plugins\configs.js:20:57)
    at C:\PROJETOS\TesteDocusaurus\my-website\node_modules\@docusaurus\core\lib\server\plugins\configs.js:99:60
    at Array.map (<anonymous>)
    at loadPluginConfigs (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\@docusaurus\core\lib\server\plugins\configs.js:99:38)
    at async initPlugins (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\@docusaurus\core\lib\server\plugins\init.js:42:27)
    at async loadPlugins (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\@docusaurus\core\lib\server\plugins\index.js:26:21)
    at async load (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\@docusaurus\core\lib\server\index.js:76:58)
    at async Command.start (C:\PROJETOS\TesteDocusaurus\my-website\node_modules\@docusaurus\core\lib\commands\start.js:42:19)
[INFO] Docusaurus version: 2.0.1
Node version: v16.16.0
```

**Additional context**
I tried to follow the [tutorial](https://sjwall.github.io/mdx-mermaid/docs/intro/), but an error shows up regarding "remarkPlugins" not being a valid field.

**Comment by sjwall** [comment]
Hey, looks like you're using the v2 rc1 release which has slightly different configuration https://sjwall.github.io/mdx-mermaid/docs/next/intro/

This might be why you're getting an error with remarkPlugins

There's a working example here https://github.com/sjwall/mdx-mermaid/blob/main/doc/docusaurus.config.js

**Comment by alexandrehtrb** [comment]
It worked! Thanks man!
