### ISSUE TITLE
Add support for mdx 3

### ISSUE THREAD

**Issue by millette** [sjwall/mdx-mermaid#97]
**Describe the solution you'd like**
Support [mdx 3](https://mdxjs.com/migrating/v3/) please :-)

**Additional context**
I was planning to use mermaid within Astro but got this error instead:

```
[@mdx-js/rollup] Cannot read properties of undefined (reading 'call')
file: /home/millette/wip/mermaid-mdx/src/pages/page-2.mdx:undefined:undefined
  Stack trace:
    at Object.transform (file:///home/millette/wip/mermaid-mdx/node_modules/.pnpm/@astrojs+mdx@3.0.1_astro@4.9.1_@types+node@18.19.33_typescript@5.4.5_/node_modules/@astrojs/mdx/dist/vite-plugin-mdx.js:54:15)
    at file:///home/millette/wip/mermaid-mdx/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19774:40
```

**Comment by sjwall** [comment]
Hi, currently I have no plans to implement support for mdx 3. A PR doing this is welcome
